
var Language = {
	informarion: "Informação",
	error: "Erro",
	warning: "Atenção",
	confirmation: "Confirmação",
	yes: "Sim",
	no: "Não",
	start: "Iniciar",
	stop: "Parar",
	server: "Servidor",
	reload: "Recarregar",
	initializing: "Inicializando",
	create: "Criado",
	uninitialized: "Não Inicializando",
	online: "On Line",
	loaded: "Carregado",
	interactive: "Interativo",
	complete: "Completo",
	authenticationRequired: "Autenticação Requerida",
	authentication: "Autenticação",
	user: "Usuário",
	secret: "Senha",
	login: "Entrar",
	logout: "Sair",
	send: "Enviar",
	clear: "Limpar",
	monastError: "Erro do MonAst",
	errorMessage: "Mensagem de Erro",
	connectionError: "Não foi possível conectar à http://#{HOSTNAME}:#{HOSTPORT} (#{RESPONSE}).<br>Verifique se o monast.py está rodando, para que o painel funcione corretamente.",
	requestError: "A requisição http://#{HOSTNAME}:#{HOSTPORT}/isAuthenticated não foi encontrada.<br>Verifique se o monast.py está rodando, para que o painel funcione corretamente.",
	internalServerError: "Recebido um \"Internal Server Error\" ao conectar à http://#{HOSTNAME}:#{HOSTPORT}/isAuthenticated.<br>Verifique os arquivos de log e reporte os erros em http://monast.sf.net",
	requestStatusError: "Ocorreu um erro ao buscar o status!<br>Por favor recarregue o Monast pressionando F5.",
	invalidUsernameSecret: "Usuário e/ou senha inválidos",
	youMustDefineAnUser: "Você deve informar um nome de usuário",
	userNotDefined: "Usuário não informado!",
	authenticatingPleaseWait: "Autenticando, por favor aguarde...",
	authenticatedReloading: "Autenticado, recarregando...",
	loggingOutPleaseWait: "Encerrando, por favor aguarde...",
	reloadNeeded: "Favor Recarregar, Pressione F5.",
	reloadingPleaseWait: "Recarregando, por favor aguarde...",
	reloadRequestedPleaseWait: "Recarregando, por favor aguarde...",
	changingServer: "Alternando Servidor...",
	cannotChangeServerOfflineReload: "Impossível mudar o servidor, Monast desconectado...<br>Favor reinicar...",
	
	mixedPannels: "Paineis",
	peersUsers: "Usuários/Ramais",
	peerUser: "Usuário/Ramal",
	meetmeRooms: "Conferências",
	meetme: "Conferência",
	parkedCallAt: "Estacionamento",
	parkedCalls: "Estacionamento",
	parkedCalls2: "Chamadas Estacionadas",
	queues: "Filas",
	asteriskCli: "Asterisk CLI",
	debug: "Debug",
	pannelsToShow: "Exibir Paineis",
	
	from: "De",
	to: "Para",
	
	noGroup: "Sem Grupo",
	originateCall: "Originar Chamada",
	viewPeerCalls: "Exibir Canais/Chamadas deste Usuário/Ramal",
	viewPeerInfo: "Exibir Informações deste Usuário/Ramal",
	execute: "Executar",
	sendResetToModem: "Enviar Reset para o Modem",
	reallyResetModem: "Você realmente precisa resetar este Canal?",
	turnMemberOf: "Adicionar Membro a Fila",
	turnMemberOfQueue: "Adicionar este Usuário como membro da Fila \"#{QUEUENAME}\"?",
	removeMemberFrom: "Remover Membro da Fila",
	removeMemberFromQueue: "Remover este Usuário/Membro da Fila \"#{QUEUENAME}\"?",
	meetmeInvite: "Convite para Conferência",
	inviteTo: "Convidar para",
	inviteToMeetme: "Convidar este Usuário para a Conferência \"#{MEETME}\"?",
	inviteNumbers: "Convidar Números",
	inviteNumbersToMeetme: "Convidar Números para Conferência",
	inviteCallToMeetme: "Convidar esta Chamada para a Conferência \"#{MEETME}\"?",
	numbers: "Números",
	onePerLine: "um por linha",
	ifNotExistsCreateDynamic: "caso esta conferência não exista,<br>uma nova conferência dinâmica será criada",
	meetmeUser: "Usuário",
	kickUser: "Excluir Usuário",
	viewMeetmeUserInfo: "Exibir Informações deste Usuário",
	requestMeetmeKickFrom: "Solicitar Exclusão deste Usuário da Conferência \"#{MEETME}\"?",
	userNumber: "Usuário Número",
	
	uniqueid: "Uniqueid",
	sourceUniqueid: "Uniqueid (origem)",
	destinationUniqueid: "Uniqueid (destino)",
	
	noActivePeerCalls: "Nenhum Canal ou Chamada ativo para este Usuário/Ramal",
	notValidCalleridNumber: "Este Usuário/Ramal não possui um Callerid (número) válido para ser transferido",
	
	selectActionForChannel: "Selecione uma ação para o canal #{UNIQUEID} (#{CHANNEL})",
	selectActionForCall: "Selecione uma ação para a chamada #{UNIQUEID} -&gt; #{BRIDGEDUNIQUEID}",
	selectChannelToTransfer: "Selecione o Canal a ser Transferido",
	selectChannelToPark: "Selecione o Canal a ser Estacionado",
	
	hangup: "Desligar",
	requestHangupChannel: "Requisitar Desligamento deste Canal?",
	requestHangupCall: "Requisitar Desligamento desta Chamada?",
	requestHangupParkedCall: "Requisitar Desligamento desta Chamada Estacionada?",
	
	channel: "Canal",
	channels: "Canais",
	channelType: "Tipo de Canal",
	channelName: "Nome do Canal",
	channelVariables: "Variáveis de Canal",
	channelsCalls: "Canais/Chamadas",
	channelMonitored: "Canal sendo Monitorado",
	channelSpyed: "Canal sendo Espionado",
	sourceChannel: "Canal de Origem",
	destinationChannel: "Canal de Destino",
	
	viewChannelInfo: "Exibir Informações do Canal",
	viewCallInfo: "Exibir Informações da Chamada",
	viewParkedCallInfo: "Exibir Informações da Chamada Estacionada",
	
	transfer: "Transferir",
	transferCall: "Transferir Chamada",
	transferDestination: "Destino da Transferência",
	transferParkedCall: "Transferir Chamada Estacionada",
	requestTransferParkedCallTo: "Requisitar Transferência desta Chamada Estacionada para o Usuário/Ramal \"#{CALLERID}\"?",
	
	reallyTransferChannelTo: "Você realmente deseja transferir o canal \"#{CHANNEL}\" para \"#{CALLERID}\"?",
	
	noSpyerNumber: "Número do Espião não informado!",
	
	spy: "Espionar",
	spyed: "Espionado",
	spyer: "Espião",
	spyerNumber: "Número do Espião",
	requestSpyChannel: "Requisitar espionagem para este canal?",
	requestSpyCall: "Requisitar espionagem para esta Chamada?",
	
	park: "Estacionar",
	
	monitored: "Monitorado",
	monitorStart: "Iniciar Monitoração",
	monitorStop: "Parar Monitoração",
	monitorToThisChannel: "Monitoração neste Canal?",
	
	peerName: "Nome do Usuário",
	peerContext: "Contexto do Usuário",
	
	callerid: "Callerid",
	calleridName: "Callerid (nome)",
	calleridNumber: "Callerid (número)",
	sourceCallerid: "Callerid (origem)",
	destinationCallerid: "Callerid (destino)",
	
	status: "Estado",
	state: "Estado",
	
	activeCalls: "Chamadas Ativas",
	
	call: "Chamada",
	calls: "chamada(s)",
	calls2: "Chamadas",
	callsAbreviated: "chmd(s)",
	callStatus: "Estado da Chamada",
	callDuration: "Duração da Chamada",
	
	exten: "Posição",
	
	parkedFrom: "Estacionado Por",
	parkedChannel: "Canal Estacionado",
	parkedCalleridName: "Canal Estacionado, Callerid (nome)",
	parkedCalleridNumber: "Canal Estacionado, Callerid (número)",
	parkedFromCalleridName: "Estacionado Por, Callerid (nome)",
	parkedFromCalleridNumber: "Estacionado Por, Callerid (número)",
	
	timeout: "Timeout",
	
	latency: "Latência",
	
	queue: "Fila",
	queueMember: "Membro",
	queueClient: "Cliente",
	statistics: "Estatísticas",
	max: "Max",
	maxCalls: "Qtd. Max. de Chamadas",
	holdtime: "Tempo de Espera",
	completed: "Completadas",
	completedCalls: "Chamadas Completadas",
	abandoned: "Abandonadas",
	abandonedCalls: "Chamadas Abandonadas",
	serviceLevel: "Nivel de Serviço",
	serviceLevelPerf: "Performance",
	weight: "Peso",
	members: "Membros",
	clients: "Clientes",
	nameLocation: "Nome/Local",
	callsTaken: "Cham. At.",
	callsTaken2: "Chamadas Atendidas",
	lastCall: "Última Chamada",
	penalty: "Penalty",
	addExternalMember: "Adicionar Membro Externo",
	viewQueueInfo: "Exibir Informações da Fila",
	memberName: "Nome do Membro",
	memberLocation: "Local do Membro",
	membership: "Tipo de Membro",
	locationFormat: "Formato: Local/&lt;numero_externo&gt;@&lt;contexto&gt;",
	answered: "Em Atendimento",
	paused: "Em Pausa",
	pauseMember: "Colocar em Pausa",
	unpauseMember: "Remover da Pausa",
	pauseThisMember: "Colocar este Membro em Pausa?",
	unpauseThisMember: "Retirar este membro da Pausa?",
	removeMember: "Remover Membro",
	removeMemberFromQueue: "Remover este Membro da Fila \"#{QUEUENAME}\"?",
	viewMemberInfo: "Exibir Informações do Membro",
	viewClientInfo: "Exibir Informações do Cliente",
	dropClient: "Remover Cliente (Desligar Chamada)",
	dropThisQueueClient: "Remover este Cliente (Desligar Chamada)?",
	position: "Posição",
	waitingSince: "Aguardando Desde",
	
	createDynamicMeetme: "Criar Conferência",
	meetme: "Conferência",
	
	_statusMap: {
		"down": "Inativo",
		"unregistered": "Não Registrado",
		"unreachable": "Inalcançável",
		"unknown": "Desconhecido",
		"unavailable": "Indisponível",
		"invalid": "Inválido",
		"busy": "Ocupado",
		"logged out": "Deslogado",
		"red alarm": "Al. Vermelho",
		"ring": "Chamando",
		"ringing": "Tocando",
		"ring, in use": "Chamando, em uso",
		"in use": "Em Uso",
		"dial": "Discando",
		"lagged": "Defasado",
		"on hold": "Em Espera",
		"off hook": "Fora do Gancho",
		"yellow alarm": "Al. Amarelo",
		"dnd enabled": "Não Perturbe",
		"blue alarm": "Al. Azul",
		"up": "Ativo",
		"link": "Ativa",
		"unlink": "Inativa",
		"registered": "Registrado",
		"reachable": "Alcançável",
		"unmonitored": "Não Monitorado",
		"not in use": "Disponível",
		"logged in": "Logado",
		"no alarm": "Sem Alarmes",
		"on hook": "No Gancho"
	}
};
