
var Language = {
	informarion: "Информация",
	error: "Ошибка",
	warning: "Предупреждение",
	confirmation: "Подтверждение",
	yes: "Да",
	no: "Нет",
	start: "Запустить",
	stop: "Остановить",
	server: "Сервер",
	reload: "Перезагрузить",
	initializing: "Инициирование",
	create: "Создание",
	uninitialized: "Неинициализирован",
	online: "Онлайн",
	loaded: "Загружено",
	interactive: "Интерактивный",
	complete: "Завершить",
	authenticationRequired: "Необходима аутентификация",
	authentication: "Аутентификация",
	user: "Пользователь",
	secret: "Пароль",
	login: "Вход",
	logout: "Выход",
	send: "Отправить",
	clear: "Очистить",
	monastError: "MonAst Ошибка",
	errorMessage: "Сообщение об ошибке",
	connectionError: "Не удалось подключиться к http://#{HOSTNAME}:#{HOSTPORT} (#{RESPONSE}).<br>Убедитесь, что monast.py запущен, чтобы панель могла правильно подключиться к порту.",
	requestError: "При запросе к http://#{HOSTNAME}:#{HOSTPORT}/isAuthenticated получен ответ \"не был найден\".<br>Убедитесь, что monast.py запущен, чтобы панель могла правильно подключиться к порту.",
	internalServerError: "Получено \"Internal Server Error\" при запросе к http://#{HOSTNAME}:#{HOSTPORT}/isAuthenticated.<br>Пожалуйста, просмотрите файл журнала и сообщите об ошибках по адресу http://monast.sf.net",
	requestStatusError: "При запросе статуса произошла ошибка!<br>Нажмите F5, чтобы перезагрузить MonAst.",
	invalidUsernameSecret: "Недействительное имя пользователя или пароль",
	youMustDefineAnUser: "Вы должны определить пользователя",
	userNotDefined: "Пользователь не определен!",
	authenticatingPleaseWait: "Аутентификация, пожалуйста, подождите...",
	authenticatedReloading: "Аутентификация, перезагрузка...",
	loggingOutPleaseWait: "Выход из системы, пожалуйста, подождите...",
	reloadNeeded: "Необходимо перезагрузить, нажмите F5.",
	reloadingPleaseWait: "Перезагрузка, подождите...",
	reloadRequestedPleaseWait: "Перезагрузка запрошена, подождите...",
	changingServer: "Смена сервера...",
	cannotChangeServerOfflineReload: "Не возможно сменить сервер, Monast не в сети...<br>Обновите страницу...",
	
	mixedPannels: "Смешанные панели",
	peersUsers: "Пиры/Пользователи",
	peerUser: "Пир/Пользователь",
	meetmeRooms: "Конференц-комнаты",
	parkedCallAt: "Припарковыный вызов на",
	parkedCalls: "Припаркованые вызовы",
	parkedCalls2: "Припаркованые вызовы",
	queues: "Очереди",
	asteriskCli: "Asterisk CLI",
	debug: "Отладка",
	pannelsToShow: "Панели для показа",
	
	from: "От",
	to: "К",
	
	noGroup: "Нет группы",
	originateCall: "Создать вызов",
	viewPeerCalls: "Просмотр пользователей/пиров каналов/звонков",
	viewPeerInfo: "Просмотр информации о пользователе/пире",
	execute: "Выполнить",
	sendResetToModem: "Послать команду сброса модему",
	reallyResetModem: "Вам действительно нужно сбросить этот канал?",
	turnMemberOf: "Включить участника",
	turnMemberOfQueue: "Вернуть этого пользователя в очередь \"#{QUEUENAME}\"?",
	removeMemberFrom: "Удалить участника из",
	meetmeInvite: "Приглашение в конференцию",
	inviteTo: "Пригласить в",
	inviteToMeetme: "Пригласите этого пользователя/пир в конференцию \"#{MEETME}\"",
	inviteNumbers: "Пригласить по номеру",
	inviteNumbersToMeetme: "Приглашение в конференцию по номерам",
	inviteCallToMeetme: "Пригласить этот вызов в конференцию \"#{MEETME}\"?",
	numbers: "Номера",
	onePerLine: "по одному в каждой строке",
	ifNotExistsCreateDynamic: "если конференция не существует,<br>то будет создана динамически",
	meetmeUser: "Участник конференции",
	kickUser: "Отключить участника",
	viewMeetmeUserInfo: "Просмотри информации об участнике",
	requestMeetmeKickFrom: "Отправить приглашение этому пользователю с конференции \"#{MEETME}\"?",
	userNumber: "Номер пользователя",

	uniqueid: "Уникальный",
	sourceUniqueid: "Уникальный источник",
	destinationUniqueid: "Уникальное направление",
	
	noActivePeerCalls: "Нет активных каналов/вызовов для этого пользователя/пира",
	notValidCalleridNumber: "У этого пользователя/пира нет допустимого номера CallerID для передачи в",
	
	selectActionForChannel: "Выберите действие для канала #{UNIQUEID} (#{CHANNEL})",
	selectActionForCall: "Выберите действие для вызова #{UNIQUEID} -&gt; #{BRIDGEDUNIQUEID}",
	selectChannelToTransfer: "Выберите канал для перевода",
	selectChannelToPark: "Выберите канал для парковки",
	
	hangup: "Завершить вызов",
	requestHangupChannel: "Разорвать этот канал?",
	requestHangupCall: "Завершить этот вызов?",
	requestHangupParkedCall: "Завершить этот припаркованный вызов?",
	
	channel: "Канал",
	channels: "Каналы",
	channelType: "Тип канала",
	channelName: "Имя канала",
	channelVariables: "Переменные канала",
	channelsCalls: "Каналы/Вызовы",
	channelMonitored: "Мониторинг канала",
	channelSpyed: "Канал прослушивается",
	sourceChannel: "Канал источник",
	destinationChannel: "Канал назначения",
	
	viewChannelInfo: "Просмотр информации о канале",
	viewCallInfo: "Просмотр информации о вызове",
	viewParkedCallInfo: "Просмотр информации о запаркованом вызове",
	
	transfer: "Перевод",
	transferCall: "Перевод вызова",
	transferDestination: "Назначение для перевода",
	transferParkedCall: "Перевод припаркованного вызова",
	requestTransferParkedCallTo: "Перевести припаркованный авыхов на пользователя/пир \"#{CALLERID}\"?",
	
	reallyTransferChannelTo: "Вы действительно хотите перевести канал \"#{CHANNEL}\" на \"#{CALLERID}\"?",
	
	noSpyerNumber: "Не указан номер прослушивающего!",
	
	spy: "Прослушивание",
	spyed: "Прослушивается",
	spyer: "Слушающий",
	spyerNumber: "Номер слушающего",
	requestSpyChannel: "Запросить прослушивание канала?",
	requestSpyCall: "Запросить прослушивание вызова?",

	park: "Парковка",
	
	monitored: "Записывается",
	monitorStart: "Начать запись",
	monitorStop: "Остановить запись",
	monitorToThisChannel: "Записывать этот канал?",
	
	peerName: "Имя пира",
	peerContext: "Контекст пира",
	
	callerid: "CallerID",
	calleridName: "CallerID Имя",
	calleridNumber: "CallerID Номер",
	sourceCallerid: "CallerID истояника",
	destinationCallerid: "CallerID назначения",
	
	status: "Статус",
	state: "Состояние",
	
	activeCalls: "Активные вызовы",
	
	call: "Вызов",
	calls: "вызов(ы)",
	calls2: "Вызовы",
	callsAbreviated: "вызов(ы)",
	callStatus: "Статус вызовы",
	callDuration: "Продолжительность вызова",
	
	exten: "Добавочный",
	
	parkedFrom: "Припаркован От",
	parkedChannel: "Припаркован канал",
	parkedCalleridName: "Припаркован CallerID Имя",
	parkedCalleridNumber: "Припаркован CallerID Номер",
	parkedFromCalleridName: "Припаркован От, CallerID Имя",
	parkedFromCalleridNumber: "Припаркован От, CallerID Номер",
	
	timeout: "Перерыв",
	
	latency: "Задержка",
	
	queue: "Очередь",
	queueMember: "Участник очереди",
	queueClient: "Пользователь очереди",
	statistics: "Статистика",
	max: "Макс.",
	maxCalls: "Макс. вызовов",
	holdtime: "Время удерживания",
	talktime: "Время разговоров",
	completed: "Завершенных",
	completedCalls: "Завершенных вызовов",
	abandoned: "Потеряных",
	abandonedCalls: "Потеряных вызовов",
	serviceLevel: "Уровень обслуживания",
	serviceLevelPerf: "Целевой уровень обсл.",
	weight: "Weight",
	members: "Участники",
	clients: "Пользователи",
	nameLocation: "Location/Name",
	callsTaken: "Принятые вызовы",
	callsTaken2: "Принятые вызовы",
	lastCall: "Последний вызов",
	penalty: "Penalty",
	addExternalMember: "ДОбавить внешнего пользователя",
	viewQueueInfo: "Просмотр информации об очереди",
	memberName: "Имя участника",
	memberLocation: "Местоположение участника",
	membership: "Членство",
	locationFormat: "Формат: Local/&lt;внешний_номер&gt;@&lt;контекст&gt;",
	stateInterface: "Состояние интерфейса",
	answered: "Отвечен",
	paused: "Перерыв",
	pauseMember: "Приостановить",
	unpauseMember: "Снять с перерыва",
	pauseThisMember: "Приостановить участника очереди?",
	unpauseThisMember: "Снять с перерыва участника очереди?",
	removeMember: "Удалить участника",
	removeMemberFromQueue: "Удалить участника очереди \"#{QUEUENAME}\"?",
	viewMemberInfo: "Просмотр информации об участнике",
	viewClientInfo: "Просмотр информации о пользователе",
	dropClient: "Сбросить пользователя (Завершить)",
	dropThisQueueClient: "Сбросить пользователя пользователя очереди?",
	position: "Позиция",
	waitingSince: "Ожидание с",
	
	createDynamicMeetme: "Создать динамическую конференцию",
	meetme: "Конференция",
	
	// Only used on other languages
	_statusMap: {
		"down": "не отвечен",
		"unregistered": "не зарегестрирован",
		"unreachable": "недоступен",
		"unknown": "неизвестно",
		"unavailable": "недоступен",
		"invalid": "недействительный",
		"busy": "занят",
		"logged out": "вышел",
		"red alarm": "красный авар.",
		"ring": "звонок",
		"ringing": "звонит",
		"ring, in use": "звонит, используется",
		"in use": "используется",
		"dial": "вызов",
		"dialing": "вызывается",
		"lagged": "запаздывает",
		"on hold": "на удержании",
		"off hook": "трубка поднят",
		"yellow alarm": "желтый авар.",
		"dnd enabled": "dnd включен",
		"blue alarm": "синий авар.",
		"up": "поднят",
		"link": "соединен",
		"unlink": "разъединен",
		"registered": "зарегистрирован",
		"reachable": "доступен",
		"unmonitored": "не записывается",
		"not in use": "не используется",
		"logged in": "вошел в систему",
		"no alarm": "нет аварий",
		"on hook": "трубка положена",
		"signal": "сигнал"
	}
};
